baseURL = 'https://act.fromour.page'
languageCode = 'en-us'
title = 'Act I Blog'
theme = 'hugo-classic'

[params]
  custom_css = ["css/a11y.css"]

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1
